name: Python CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]
  workflow_dispatch:

jobs:
  validation:
    strategy:
      fail-fast: false
      matrix:
        python:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"

    uses: YaoYinYing/action-python/.github/workflows/validation.yml
    with:
      workdir: '.'
      python-version: ${{ matrix.python }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}



  publish:
    strategy:
      fail-fast: false

    uses: microsoft/action-python/.github/workflows/publish.yml@2f264485f12c1cc0b72a6fe24752b9ae9ba0b934
    secrets:
      PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      TEST_PYPI_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD  }}
