name: Pylint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [created]
  workflow_dispatch:

env:
  lint-python-version: "3.11"

jobs:
  UpdateLinting:
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Linting
        uses: YaoYinYing/fuck-u-code-github-action@144cfe0dd1d01e5c5f66ee2faf4f61a200dc93b4
        with:
          target-path: src # scan src package only
          reverse-score: "true"
          badge-text: fuck-u-code score
          badge-file-name: fuck-u-code_scan
          badge-logo-id: python
          badge-artifact-name: upload-my-awesome-badge-${{ github.run_id }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          R2_BUCKET: ${{ secrets.R2_BUCKET }}
          R2_badge_path: badge_dir_with_uniq_name/RosettaPy/fuck-u-code
